### ISSUE TITLE
Not building with 4coder 4.1.7

### ISSUE THREAD

**Issue by samwdp** [TheSandvichMaker/4coder-vimmish#3]
Newly extracted 4coder 4.1.7
Added 4coder_vimmish and clearfield into custom folder.

created new custom from 4coder_default_bindings

Added  to end of custom_layer_init
```
vim_init(app);
vim_set_default_hooks(app);
vim_setup_default_mapping(app, &framework_mapping, vim_key(KeyCode_Space));
```

buildsuper win64

4coder\custom\4coder_vimmish.cpp(260): error C2065: 'Data': undeclared identifier
4coder\custom\4coder_vimmish.cpp(260): error C2146: syntax error: missing ';' before identifier 'memory'
4coder\custom\4coder_vimmish.cpp(260): error C2065: 'memory': undeclared identifier
4coder\custom\4coder_vimmish.cpp(261): error C2065: 'memory': undeclared identifier
4coder\custom\4coder_vimmish.cpp(262): error C2065: 'memory': undeclared identifier
4coder\custom\4coder_vimmish.cpp(295): error C2065: 'Data': undeclared identifier
4coder\custom\4coder_vimmish.cpp(295): error C2146: syntax error: missing ';' before identifier 'memory'
4coder\custom\4coder_vimmish.cpp(295): error C2065: 'memory': undeclared identifier
4coder\custom\4coder_vimmish.cpp(298): error C2065: 'memory': undeclared identifier
4coder\custom\4coder_vimmish.cpp(302): error C2065: 'memory': undeclared identifier
4coder\custom\4coder_vimmish.cpp(303): error C2065: 'memory': undeclared identifier
4coder\custom\4coder_vimmish.cpp(1951): error C2065: 'mapid_file': undeclared identifier
4coder\custom\4coder_vimmish.cpp(4418): error C2065: 'global_config': undeclared identifier
4coder\custom\4coder_vimmish.cpp(4436): error C2065: 'global_config': undeclared identifier
4coder\custom\4coder_vimmish.cpp(5496): error C2065: 'global_config': undeclared identifier
4coder\custom\4coder_vimmish.cpp(5513): error C2065: 'global_config': undeclared identifier
4coder\custom\4coder_vimmish.cpp(5518): error C2065: 'global_config': undeclared identifier
4coder\custom\4coder_vimmish.cpp(5518): error C2065: 'global_config': undeclared identifier
4coder\custom\4coder_vimmish.cpp(5522): error C2065: 'global_config': undeclared identifier
4coder\custom\4coder_vimmish.cpp(5527): error C2065: 'global_config': undeclared identifier
4coder\custom\4coder_vimmish.cpp(5536): error C2065: 'global_config': undeclared identifier
4coder\custom\4coder_vimmish.cpp(5542): error C2065: 'global_config': undeclared identifier
4coder\custom\4coder_vimmish.cpp(5840): error C2065: 'global_config': undeclared identifier
4coder\custom\4coder_vimmish.cpp(5851): error C2065: 'global_config': undeclared identifier
4coder\custom\4coder_vimmish.cpp(5872): error C2065: 'global_config': undeclared identifier
4coder\custom\4coder_vimmish.cpp(6065): error C2065: 'mapid_global': undeclared identifier
4coder\custom\4coder_vimmish.cpp(6098): error C2065: 'mapid_file': undeclared identifier
4coder\custom\4coder_vimmish.cpp(6237): error C2065: 'mapid_global': undeclared identifier
4coder\custom\4coder_vimmish.cpp(6281): error C2065: 'mapid_file': undeclared identifier
4coder\custom\4coder_vimmish.cpp(6282): error C2065: 'mapid_global': undeclared identifier
4coder\custom\4coder_vimmish.cpp(6332): error C2065: 'mapid_code': undeclared identifier
4coder\custom\4coder_vimmish.cpp(6333): error C2065: 'mapid_file': undeclared identifier
4coder\custom\4coder_vimmish.cpp(6379): error C2065: 'mapid_global': undeclared identifier

**Comment by TheSandvichMaker** [comment]
I made it build now, sorry for the delay. For now, to get it to work with 4.1.7, you must delete your bindings.4coder file.
